### ekf config file ###
ekf_filter_node:
  ros__parameters:
    use_sim_time: False

    frequency: 30.0
    two_d_mode: true

    map_frame: map
    odom_frame: odom
    base_link_frame: base_footprint
    world_frame: odom

    odom0: diffbot_base_controller/odom
    imu0: imu_broadcaster/imu

    #        [x_pos   , y_pos    , z_pos,
    #         roll    , pitch    , yaw,
    #         x_vel   , y_vel    , z_vel,
    #         roll_vel, pitch_vel, yaw_vel,
    #         x_accel , y_accel  , z_accel]

    odom0_queue_size: 2
    odom0_nodelay: false
    odom0_differential: false


    imu0_config: [false, false, false,  # x, y, z position (typically false for 2D localization)
              false, false, false,  # roll, pitch, yaw orientation (set true for yaw if needed)
              false, false, false,  # x, y, z linear velocity
              false, false, true,   # roll, pitch, yaw angular velocity
              true, true, true]     # x, y, z linear acceleration

    imu0_differential: false

    #        [x_pos   , y_pos    , z_pos,
    #         roll    , pitch    , yaw,
    #         x_vel   , y_vel    , z_vel,
    #         roll_vel, pitch_vel, yaw_vel,
    #         x_accel , y_accel  , z_accel]
    
