teleop_twist_joy_node:
  ros__parameters:
    axis_linear:
      x: 4
    scale_linear:
      x: 0.6

    axis_angular:
      yaw: 0
    scale_angular:
      yaw: 0.5

    axis_linear_reverse:
      x: 5
    scale_linear_reverse:
      x: 0.4

    publish_stamped_twist: True

    require_enable_button: False

