<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >

    <xacro:property name="camera_radius" value="0.015"/>
    <xacro:property name="camera_length" value="0.085"/>

    <xacro:property name="camera_x_offset" value="0.02"/>

    <xacro:property name="camera_density" value="2710.0"/>

    <xacro:property name="camera_mass" value="${camera_density*pi_const*camera_radius*camera_radius*camera_length}"/>
    
    <!-- CAMERA LINK -->

	<joint name="camera_joint" type="fixed">
        <parent link="camera_mount"/>
        <child link="camera_frame"/>
        <origin xyz="${camera_x_offset} 0 ${camera_mount_z_dim/2+camera_radius}" />
    </joint>

    <link name="camera_frame">
        <visual>
            <origin rpy="${pi_const/2} 0 0"/>
            <geometry>
                <cylinder radius="${camera_radius}" length="${camera_length}"/>
            </geometry>
            <material name="black"/>
        </visual>

        <collision>
            <origin rpy="${pi_const/2} 0 0"/>
            <geometry>
                <cylinder radius="${camera_radius}" length="${camera_length}"/>
            </geometry>
        </collision>
        
        <inertial>
            <origin rpy="${pi_const/2} 0 0"/>
            <mass value="${camera_mass}"/>
            <inertia ixx="${(1.0/12.0)*camera_mass*(3.0*camera_radius*camera_radius+camera_length*camera_length)}" ixy="0.0" ixz="0.0" iyy="${(1.0/12.0)*camera_mass*(3.0*camera_radius*camera_radius+camera_length*camera_length)}" iyz="0.0" izz="${0.5*camera_mass*camera_radius*camera_radius}" />
        </inertial>
    </link>
    
    <joint name="camera_optical_joint" type="fixed">
        <parent link="camera_frame"/>
        <child link="camera_optical_frame"/>
        <origin xyz="0 0 0" rpy="${-pi_const/2} 0 ${-pi_const/2}"/> 
    </joint>

    <link name="camera_optical_frame"></link>

    <gazebo reference="camera_frame">

        <material>Gazebo/Black</material>

        <sensor name="camera" type="camera">
            <pose> camera_radius 0 0 0 0 0 </pose>
            <visualize>false</visualize>
            <update_rate>10</update_rate>
            <camera>
                <horizontal_fov>1.089</horizontal_fov>
                <image>
                    <format>R8G8B8</format>
                    <width>640</width>
                    <height>480</height>
                </image>
                <clip>
                    <near>0.05</near>
                    <far>8.0</far>
                </clip>
            </camera>

            <plugin name="camera_controller" filename="libgazebo_ros_camera.so">
                <frame_name>camera_optical_frame</frame_name>
            </plugin>
        </sensor>

    </gazebo>

</robot>