<?xml version="1.0"?>

<robot>
    <gazebo>
        <plugin name="diff_drive" filename="libgazebo_ros_diff_drive.so">

            <!-- Wheel Information -->
            <left_joint>left_wheel_joint</left_joint>
            <right_joint>right_wheel_joint</right_joint>
            <wheel_separation>${main_body_y_dim+wheel_link_length}</wheel_separation>
            <wheel_diameter>${2*wheel_link_radius}</wheel_diameter>


            <!-- Limits -->
            <max_wheel_torque>20</max_wheel_torque>
            <max_wheel_acceleration>2</max_wheel_acceleration>

            
            <!-- Output -->
            <odometry_frame>odom</odometry_frame>
            <robot_base_frame>base_footprint</robot_base_frame>

            <publish_odom>true</publish_odom>
            <publish_odom_tf>true</publish_odom_tf>
            <publish_wheel_tf>true</publish_wheel_tf>

            <publish_wheel_joint_state>true</publish_wheel_joint_state>
            <command_topic>cmd_vel</command_topic>
            <odometry_topic>odom</odometry_topic>

        </plugin>
    </gazebo>

</robot>