teleop_node:
    ros__parameters:
      axis_linear:
        x: 4
      scale_linear:
        x: 0.5

      axis_angular:
        yaw: 0
      scale_angular:
        yaw: 0.5

    #enable_button: 6

    #require_enable_button: true
    