controller_manager:
  ros__parameters:
    update_rate: 30 # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diffbot_base_controller:
      type: diff_drive_controller/DiffDriveController

    imu_broadcaster:
      type: imu_sensor_broadcaster/IMUSensorBroadcaster

diffbot_base_controller:
  ros__parameters:
    left_wheel_names: ["left_wheel_joint"]
    right_wheel_names: ["right_wheel_joint"]

    wheel_separation: 0.368
    wheel_radius: 0.08255

    wheel_separation_multiplier: 2.0
    left_wheel_radius_multiplier: 0.5
    right_wheel_radius_multiplier: 0.5

    publish_rate: 50.0
    use_stamped_vel: false

    base_frame_id: base_footprint

    pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]

    open_loop: false
    enable_odom_tf: false

    cmd_vel_timeout: 0.5
    publish_limited_velocity: false
    velocity_rolling_window_size: 15

    # Velocity and acceleration limits
    # Whenever a min_* is unspecified, default to -max_*
    linear.x.has_velocity_limits: true
    linear.x.has_acceleration_limits: true
    linear.x.has_jerk_limits: false
    linear.x.max_velocity: 0.2
    linear.x.min_velocity: -0.2
    linear.x.max_acceleration: 0.5
    linear.x.min_acceleration: -0.5
    linear.x.max_jerk: 0.0
    linear.x.min_jerk: 0.0

    angular.z.has_velocity_limits: true
    angular.z.has_acceleration_limits: true
    angular.z.has_jerk_limits: false
    angular.z.max_velocity: 0.25
    angular.z.min_velocity: -0.25
    angular.z.max_acceleration: 0.4
    angular.z.min_acceleration: -0.4
    angular.z.max_jerk: 0.0
    angular.z.min_jerk: 0.0

imu_broadcaster:
  ros__parameters:
    sensor_name: mpu6050
    frame_id: imu_frame

    # 500 data points used to calculated covariances
    static_covariance_orientation:
      [4.28344e-06, 0.0, 0.0, 3.14644e-06, 0.0, 0.0, 5.3342e-07, 0.0, 0.0]
    static_covariance_angular_velocity:
      [2.80206e-07, 0.0, 0.0, 4.95924e-07, 0.0, 0.0, 4.20313e-07, 0.0, 0.0]
    static_covariance_linear_acceleration:
      [0.000338634, 0.0, 0.0, 0.000365971, 0.0, 0.0, 0.000522409, 0.0, 0.0]
